### ISSUE TITLE
Home page graphics missing

### ISSUE THREAD

**Issue by MagnificentF** [MagnificentF/magnificentf.github.io#11]
Steps to reproduce:
Go to http://magnificentf.github.io/

Results:
Examples of artistic content are absent

Expected:
Examples of artistic content are present, below the subheading sections, when clicked, each links to its corresponding page (Illustration, Painting, Sculpture, Animation, Contact, About)

**Comment by jessehattabaugh** [comment]
Wireframes would help clarify the expectiation of this issue. Even just a pic of a drawing of what you want it to look like.
