### ISSUE TITLE
point missf.net at github.io

### ISSUE THREAD

**Issue by MagnificentF** [MagnificentF/magnificentf.github.io#9]
Steps to reproduce:
go to http://www.missf.net

Results:
Forbidden
You don't have permission to access / on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Expected results:
Expected the content of this repo to show up
Also expected http://missf.net to display contents of this repo
Expected a favicon to show up

**Comment by jessehattabaugh** [comment]
fixed!
